version: "2"
services:
  python:
    build: .
    container_name: python
    ports:
     - 8080:8080
    volumes:
     - .:/usr/src/car
    environment:
     - FLASK_APP=app.py
    working_dir: /usr/src/car
    command: flask run --host=0.0.0.0 --port=8080
  autosuggest:
    build: autosuggest/
    container_name: autosugg
    ports:
     - 1081:1081
    volumes:
     - ./autosuggest/autosuggest:/usr/src/autosuggest
    environment:
        - ABC=abc
    working_dir: /usr/src/autosuggest
    command: mvn exec:java

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  nginx:
      image: nginx
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ../html:/usr/share/nginx/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  esdata:
    driver: local
